"""Changed ununique constraints on Food and Meal 'name' attribute so different users can add foods with the same name

Revision ID: 3c77a1324219
Revises: a9dfc4f53191
Create Date: 2025-07-09 22:54:38.640176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c77a1324219'
down_revision = 'a9dfc4f53191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Foods_name'))
        batch_op.create_index(batch_op.f('ix_Foods_name'), ['name'], unique=False)

    with op.batch_alter_table('Meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Meals_name'))
        batch_op.create_index(batch_op.f('ix_Meals_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Meals_name'))
        batch_op.create_index(batch_op.f('ix_Meals_name'), ['name'], unique=1)

    with op.batch_alter_table('Foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Foods_name'))
        batch_op.create_index(batch_op.f('ix_Foods_name'), ['name'], unique=1)

    # ### end Alembic commands ###
