"""empty message

Revision ID: c1d164a09614
Revises: 3c77a1324219
Create Date: 2025-07-10 23:47:13.754831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d164a09614'
down_revision = '3c77a1324219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Meal_Food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['Foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['Meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meal_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_items',
    sa.Column('meal_id', sa.INTEGER(), nullable=False),
    sa.Column('food_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['Foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['Meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'food_id')
    )
    op.drop_table('Meal_Food')
    # ### end Alembic commands ###
