"""empty message

Revision ID: a8dd00081dad
Revises: d91ee0a6a493
Create Date: 2025-07-08 01:29:48.152142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8dd00081dad'
down_revision = 'd91ee0a6a493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['Foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['Meals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_log_date'), ['log_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_log_date'))

    op.drop_table('daily_log')
    # ### end Alembic commands ###
