"""empty message

Revision ID: d91ee0a6a493
Revises: 24f636ca44ee
Create Date: 2025-07-08 01:08:38.845871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ee0a6a493'
down_revision = '24f636ca44ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_items',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['Foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['Meals.id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_items')
    # ### end Alembic commands ###
